config/routes.rb
Rails.application.routes.draw do
  
  resources 'stats'
  root 'stats#index'
  post 'post/:mac' => 'sensor#receive'
end

app/models/device.rb
class String
  def is_json?
    begin
      !!JSON.parse(self)
    rescue
      false
    end
  end
end

class Device < ActiveRecord::Base
  has_many :measurements

  def self.load
    buckets_url = 'http://blackbird.datamol.net:8098/types/counters/buckets?buckets=true'
    buckets = JSON.load(Faraday.get(buckets_url).body)["buckets"]

    buckets.each do |bucket|
      Device.where(mac: bucket.split('_').last).first_or_create
    end
  end

  def load_keys
    host = 'http://blackbird.datamol.net:8098'
    url = "#{host}/types/counters/buckets/weather_proxy_1_#{mac}/keys?keys=true"
    JSON.load(Faraday.get(url).body)["keys"]
  end

  def load_keydata(key)
    host = 'http://blackbird.datamol.net:8098'
    url = "#{host}/types/counters/buckets/weather_proxy_1_#{mac}/keys/#{key}"
    body = Faraday.get(url).body
    # JSON.load(body) if body.is_json?
    if body.is_json?
      JSON.load(body)
    else
      vtag = body.split("\n").second
      url = url + "?vtag=#{vtag}"
      JSON.load(Faraday.get(url).body)
    end
  end

  def sync_data
    keys = load_keys
    old_keys = measurements.pluck(:riak_key)


    (keys-old_keys).sort.each do |key|
      m = measurements.where(riak_key: key).first_or_create
      if !m.temperature
        key_data = load_keydata(key)
        if key_data
          m.temperature = key_data['temperature']
          m.pressure = key_data['pressure']
          m.humidity = key_data['humidity']
          m.measured_at = Time.at(key.split('_').last.to_i)
          m.save
        end
      end
    end
  end


end

app/models/measurement.rb
class Measurement < ActiveRecord::Base

  def self.last_day(quantity)
    current_hour = DateTime.now.hour
    hours = current_hour.
      downto(current_hour-23).
      map{|h| h%24 }.
      reverse

    temps = Measurement.
      group('EXTRACT(HOUR FROM created_at)::int').
      order('EXTRACT(HOUR FROM created_at)::int').
      average(quantity)

    values = hours.
      map{ |h| temps[ (h-3)%24 ].to_f }

    Hash[hours.zip(values)]
  end

  def self.by_hours(quantity)
    pairs = Measurement.
      group("date_trunc('hour',measured_at)").
      order("date_trunc('hour',measured_at)"). 
      pluck("extract(epoch from date_trunc('hour',measured_at)), avg(#{quantity})").
      map{ |t| [t.first.to_i*1000,t.last.round(2)] if t.last!=nil }.
      compact

    #fill with NaN's
    t1 = pairs.first.first
    t2 = pairs.last.first
    ts = (t1..t2).step(3600000).to_a

    pairs = Hash[pairs]
    ts.map{ |t| [t, pairs[t]] }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sensor_controller.rb
class SensorController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:receive]

  def receive
    m = Measurement.create(measurement_params)
    m.measured_at = m.created_at
    m.device_id = Device.where(mac:m.mac).first_or_create.id
    m.save
    render :json => m
  end

  private

    def measurement_params
      params.permit(:temperature,:pressure,:humidity,:mac)
    end

end

app/controllers/stats_controller.rb
class StatsController < ApplicationController

  def index
    @devices = Device.order(:mac).all
  end

  def show
    dev = Device.find(params[:id])
    @temp = dev.measurements.by_hours("temperature")
    @humidity = dev.measurements.by_hours("humidity")
    @pressure = dev.measurements.by_hours("pressure")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sensor_helper.rb
module SensorHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Birds</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
    	<%= yield %>
    </div>
  </body>  
</html>

app/views/stats/index.html.erb
<div class="row">
  <div class="col-sm-1">
  </div>
  <div class="col-sm-10 rcol">

    <div class="row">

  <br><br>
      <div class="panel panel-default">
        <div class="panel-heading">Devices</div>
        <table class="table table-striped">
          <tr>
            <th>Owner</th>
            <th>MAC address</th>
            <th>Measurements count</th>
            <th>First measurement</th>
            <th>Last measurement</th>
          </tr>
          <% @devices.each do |d| %>
          <% next if d.measurements.where("measured_at is not null").empty? %>
          <% Rails.logger.info "---#{d.id}" %>
          <tr>
            <td><%= d.owner %></td>
            <td><%= link_to d.mac, stat_url(d.id) %></td>
            <td><%= d.measurements.count %></td>
            <td><%= d.measurements.order(:measured_at).where("measured_at is not null").first.measured_at.to_date %></td>
            <td><%= d.measurements.order(:measured_at).where("measured_at is not null").last.measured_at.to_date %></td>
          </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

<br><br>

app/views/stats/show.html.erb
<script type="text/javascript">

$(function () {
  // Create the chart
  $('#temp').highcharts('StockChart', {
    rangeSelector : { selected : 1 },
    title : { text : 'Temperature' },
    series : [{
      name : 'Temperature',
      data : <%= @temp.to_json.html_safe %>,
      type : 'areaspline',
      threshold : null,
      tooltip : {
        valueDecimals : 2
      },
      fillColor : {
        linearGradient : {
          x1: 0,
          y1: 0,
          x2: 0,
          y2: 1
        },
        stops : [
          [0, Highcharts.getOptions().colors[0]],
          [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
        ]
      }
    }]
  });


  // Create the chart
  $('#humidity').highcharts('StockChart', {
    rangeSelector : { selected : 1 },
    title : { text : 'Humidity' },
    series : [{
      name : 'Humidity',
      data : <%= @humidity.to_json.html_safe %>,
      type : 'areaspline',
      threshold : null,
      tooltip : {
        valueDecimals : 2
      },
      fillColor : {
        linearGradient : {
          x1: 0,
          y1: 0,
          x2: 0,
          y2: 1
        },
        stops : [
          [0, Highcharts.getOptions().colors[0]],
          [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
        ]
      }
    }]
  });


  // Create the chart
  $('#pressure').highcharts('StockChart', {
    rangeSelector : { selected : 1 },
    title : { text : 'Pressure' },
    series : [{
      name : 'Pressure',
      data : <%= @pressure.to_json.html_safe %>,
      type : 'areaspline',
      threshold : null,
      tooltip : {
        valueDecimals : 2
      },
      fillColor : {
        linearGradient : {
          x1: 0,
          y1: 0,
          x2: 0,
          y2: 1
        },
        stops : [
          [0, Highcharts.getOptions().colors[0]],
          [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
        ]
      }
    }]
  });

});
</script>


<div class="row">
  <div class="col-sm-1">
  </div>

  <div class="col-sm-10 rcol">

    <div class="row">
      <h3 class="page-header">Temperature</h3>
      <div id="temp" width="800" height="300"></div>
    </div>

    <div class="row">
      <h3 class="page-header">Humidity</h3>
      <div id="humidity" width="800" height="300"></div>
    </div>

    <div class="row">
      <h3 class="page-header">Pressure</h3>
      <div id="pressure" width="800" height="300"></div>
    </div>

  </div>
</div>